language: rust

rust:
  - stable
  - nightly

cache: cargo

before_script:
- "( cargo install diesel_cli || true )"
- export PATH=$HOME/.cargo/bin:$PATH
- mkdir -p $HOME/.tick/db
- cp ./.env.example ./.env
- diesel setup
