[package]
name = "tick"
version = "0.2.0"
authors = ["Roger Steve Ruiz <hi@rog.gr"]
description = "A time-tracking cli tool that generates useful reports for the last week."
repository = "https://github.com/rogeruiz/tick"
readme = "README.md"
keywords = [
  "cli",
  "timekeeping",
  "time-tracking"
]
license = "MIT"

[dependencies]
diesel = "0.8.0"
diesel_codegen = { version = "0.8.0", features = [ "sqlite" ] }
dotenv = "0.8.0"
chrono = "0.2.22"

[dependencies.clap]
version = "2"
features = [
  "suggestions",
  "color",
  "wrap_help",
  "yaml",
]
