name: tick
args:
  - name: &name
      short: n
      long: name
      help: Set a name for this timer.
      takes_value: true
  - entry: &entry
      short: e
      long: entry
      help: Set a message for this timer.
      takes_value: true
  - verbose:
      short: v
      long: verbose
      multiple: false
      help: Sets the level of verbosity.
subcommands:
  - start:
      about: Start a ticking timer.
      args:
        - name: *name
        - entry: *entry
  - stop:
      about: Stop a ticking timer.
      args:
        - name: *name
        - entry: *entry
